version: '3.8'

services:
  ollama_server:
    image: ollama/ollama
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 3 &&
      ollama pull codegemma &&
      wait"
  
  flask_app:
    build: .
    container_name: flask_app
    depends_on:
      - ollama_server
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  ollama_data:
